version: 0.2

env:
  variables:
    S3_BUCKET: "splunk-deployment-test"
    EMAIL: "$EMAIL"  # Passed from Lambda response
    # These would be passed from Lambda response via environment variables
    INVENTORY_S3_PATH: "$INVENTORY_S3_PATH"
    GROUP_VARS_S3_PATH: "$GROUP_VARS_S3_PATH"
    KEY_FILES: "$KEY_FILES"  # Space-separated list of key filenames

cache:
  paths:
    - /root/terraform_cache/**/*
    - /root/.ansible_cache/**/*

phases:
  install:
    commands:
      - cd Cluster-Configuration
      - echo Installing Ansible, and boto3...
      - mkdir -p /root/terraform_cache /root/.ansible_cache
      - if ! ansible --version > /dev/null 2>&1; then
          echo "Installing Ansible..." &&
          yum install -y unzip wget ansible;
        else
          echo "Ansible already installed.";
        fi
      - ansible --version

      # ✅ Install boto3 for Python
      - echo "Installing boto3..."
      - pip3 install boto3

      # Create necessary directories
      - mkdir -p /root/.ssh
      - mkdir -p group_vars
      
      # Download keys
      - for key in $KEY_FILES; do
          aws s3 cp s3://$S3_BUCKET/clients/$EMAIL/keys/$key /root/.ssh/$key;
          chmod 600 /root/.ssh/$key;
        done
      
      # Download inventory files
      - aws s3 cp $INVENTORY_S3_PATH ./inventory.ini
      - aws s3 cp $GROUP_VARS_S3_PATH ./group_vars/all.yml
      
      # Download instance_ids.txt file
      - aws s3 cp s3://$S3_BUCKET/cluster-templates/final/$EMAIL/instance_ids.txt ./instance_ids.txt

  build:
    commands:
      - ansible-playbook -i inventory.ini site.yml

  post_build:
    commands:
      - echo "EC2 Splunk + Ansible Deployment Completed Successfully!"
      - |
        if [ -f instance_ids.txt ]; then
          echo "Stopping instances listed in instance_ids.txt..."
          INSTANCE_IDS=$(tr '\n' ' ' < instance_ids.txt)
          aws ec2 stop-instances --instance-ids $INSTANCE_IDS
          echo "Stopped instances: $INSTANCE_IDS"
        else
          echo "instance_ids.txt not found - skipping instance stop"
        fi
      - echo "Build completed at $(date)"