---
- name: Install and configure OSSEC on Ubuntu
  hosts: all
  become: yes
  vars:
    ossec_version: "3.7.0"
    ossec_tarball: "ossec-hids-{{ ossec_version }}.tar.gz"
    ossec_url: "https://github.com/ossec/ossec-hids/archive/{{ ossec_version }}.tar.gz"
    ossec_dir: "ossec-hids-{{ ossec_version }}"

  tasks:
    - name: Update and upgrade system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Add repository for legacy PHP
      apt:
        name: software-properties-common
        state: present

    - name: Add Ondrej PHP PPA
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Install required packages
      apt:
        name:
          - build-essential
          - gcc
          - make
          - apache2
          - libapache2-mod-php7.0
          - php7.0
          - php7.0-cli
          - php7.0-common
          - apache2-utils
          - unzip
          - wget
          - sendmail
          - inotify-tools
          - libevent-dev
          - zlib1g-dev
          - libssl-dev
          - libpcre2-dev
          - libsystemd-dev
          - expect
        state: present

    - name: Ensure /opt/ directory exists
      file:
        path: /opt
        state: directory
        mode: '0755'

    - name: Download OSSEC tarball
      get_url:
        url: https://github.com/ossec/ossec-hids/archive/refs/tags/3.7.0.tar.gz
        dest: /opt/ossec.tar.gz

    - name: Extract OSSEC tarball
      unarchive:
        src: /opt/ossec.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create preloaded-vars.conf
      copy:
        dest: "/opt/ossec-hids-3.7.0/etc/preloaded-vars.conf"
        content: |
          USER_LANGUAGE="en"
          INSTALL_TYPE="local"
          DIR="/var/ossec"
          EMAIL_NOTIFICATION="yes"
          EMAIL_TO="root@localhost"
          SMTP_SERVER="localhost"
          EMAIL_FROM="ossec@localhost"
          SYS_CHECK="yes"
          ROOTKIT="yes"
          ACTIVE_RESPONSE="yes"
          FIREWALL_DROP="yes"
          WHITE_LIST="no"

    - name: Run OSSEC install non-interactively
      command: ./install.sh
      args:
        chdir: /opt/ossec-hids-3.7.0

    - name: Start OSSEC service
      command: /var/ossec/bin/ossec-control start

    - name: Check if OSSEC is running
      shell: /var/ossec/bin/ossec-control status
      register: ossec_status
      changed_when: false

    - name: Print OSSEC status
      debug:
        var: ossec_status.stdout_lines

