---
- name: Install and configure OpenVPN Access Server on Ubuntu 22.04
  hosts: openvpn
  become: true
  tasks:

    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - curl
          - ca-certificates
          - tzdata
        state: present

    - name: Configure timezone
      command: dpkg-reconfigure -f noninteractive tzdata

    - name: Download and install OpenVPN Access Server using official script
      shell: |
        curl -fsS https://packages.openvpn.net/as/install.sh | bash -s -- --yes
      args:
        executable: /bin/bash

    - name: Set password for 'openvpn' user
      command: >
        /usr/local/openvpn_as/scripts/sacli --user openvpn --new_pass 'SoftMania@123' SetLocalPassword

    - name: Create VPN user 'ubuntu' with password
      command: >
        /usr/local/openvpn_as/scripts/sacli --user ubuntu --new_pass 'SoftMania@123' SetLocalPassword

    - name: Grant admin access to 'ubuntu' user
      command: >
        /usr/local/openvpn_as/scripts/sacli --user ubuntu --key "prop_superuser" --value "true" UserPropPut

    - name: Restart OpenVPN Access Server
      systemd:
        name: openvpnas
        state: restarted
        enabled: true