---
- name: Install and configure OpenVPN Access Server on Ubuntu 22.04
  hosts: openvpn
  become: true
  vars:
    vpn_admin_user: "ubuntu"
    vpn_admin_password: "SoftMania@123"
    default_user_password: "SoftMania@123"

  tasks:

    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - curl
          - ca-certificates
          - tzdata
        state: present

    - name: Configure timezone
      command: dpkg-reconfigure -f noninteractive tzdata

    - name: Copy OpenVPN install script to target
      copy:
        src: scripts/openvpn_install.sh
        dest: /tmp/openvpn_install.sh
        mode: '0755'

    - name: Run OpenVPN install script
      shell: bash /tmp/openvpn_install.sh

    - name: Set password for 'openvpn' default user
      command: >
        /usr/local/openvpn_as/scripts/sacli --user openvpn --new_pass '{{ default_user_password }}' SetLocalPassword

    - name: Create VPN admin user '{{ vpn_admin_user }}' with password
      command: >
        /usr/local/openvpn_as/scripts/sacli --user '{{ vpn_admin_user }}' --new_pass '{{ vpn_admin_password }}' SetLocalPassword

    - name: Grant admin access to '{{ vpn_admin_user }}'
      command: >
        /usr/local/openvpn_as/scripts/sacli --user '{{ vpn_admin_user }}' --key "prop_superuser" --value "true" UserPropPut

    - name: Restart OpenVPN Access Server
      systemd:
        name: openvpnas
        state: restarted
        enabled: true

    - name: Show Web UI Access Info
      debug:
        msg: |
          ✅ OpenVPN Access Server installation complete!
          🌐 Web UI: https://{{ ansible_host }}:943/admin
          👤 Admin user: {{ vpn_admin_user }}
          🔑 Password: {{ vpn_admin_password }}